apiVersion: v1
kind: Service
metadata:
  name: prometheus-lb
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus-lb
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: monitoring
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  externalTrafficPolicy: Cluster