apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter-config
  namespace: monitoring
  labels:
    app: snmp-exporter
    monitoring: prometheus
data:
  snmp.yml: |
    modules:
      if_mib:
        walk:
          - 1.3.6.1.2.1.2
          - 1.3.6.1.2.1.31
        version: 2
        auth:
          community: public
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
        - name: snmp-exporter
          image: prom/snmp-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - --config.file=/etc/snmp/snmp.yml
          ports:
            - name: http-metrics
              containerPort: 9116
          volumeMounts:
            - name: snmp-config
              mountPath: /etc/snmp
              readOnly: true
      volumes:
        - name: snmp-config
          configMap:
            name: snmp-exporter-config
            items:
              - key: snmp.yml
                path: snmp.yml
---
apiVersion: v1
kind: Service
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  type: ClusterIP
  selector:
    app: snmp-exporter
  ports:
    - name: http-metrics
      port: 9116
      targetPort: http-metrics
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    release: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  selector:
    matchLabels:
      app: snmp-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
      params:
        module:
          - if_mib
        target:
          - 172.16.40.1:161
          - 172.16.10.2:161