---
- name: Check if Cilium is already installed
  ansible.builtin.shell: kubectl get pods -n kube-system -l k8s-app=cilium --no-headers | wc -l
  register: cilium_pods_count
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  failed_when: false
  changed_when: false

- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: cilium_pods_count.stdout | int == 0

- name: Install Cilium CNI
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values:
      operator:
        replicas: 1
      hubble:
        relay:
          enabled: true
        ui:
          enabled: true
      ipam:
        mode: kubernetes
      kubeProxyReplacement: strict
      k8sServiceHost: "{{ api_vip | default('172.16.40.100') }}"
      k8sServicePort: 8443
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: cilium_pods_count.stdout | int == 0

- name: Wait for Cilium pods to be ready
  ansible.builtin.shell: |
    kubectl wait --for=condition=ready pod -l k8s-app=cilium -n kube-system --timeout=300s
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: cilium_pods_count.stdout | int == 0