apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - storageclass.yaml
  - minio.yaml
  - minio-bootstrap.yaml
  - monitoring.yaml
  - networkpolicy.yaml
