apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: logging
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/name: minio
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  endpoints:
    - port: api
      path: /minio/v2/metrics/cluster
      interval: 30s
      scrapeTimeout: 10s
