apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pbs-observer
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["portal"]
  selector:
    matchLabels:
      app.kubernetes.io/name: pbs-observer
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - targetLabel: job
          replacement: pbs-observer
