---
- name: Ensure HAProxy is installed
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Deploy HAProxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  notify: Restart HAProxy

- name: Ensure HAProxy service is enabled and running
  ansible.builtin.service:
    name: haproxy
    enabled: true
    state: started