apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: portal
resources:
  - workload.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: pbs-observer-code
    files:
      - exporter.py
  - name: pbs-observer-ca
    files:
      - pbs-ca.pem
