- name: Deploy kubeadm join config file
  become: yes
  template:
    src: join_kubeadm_wk.yaml
    dest: /root/join_kubeadm_wk.yaml

- name: Execute kubeadm join command
  become: yes
  shell: "kubeadm join --config /root/join_kubeadm_wk.yaml"
