apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: cluster-wide-apps
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.5.7
    helm:
      releaseName: argocd
      values: |
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
            maxReplicas: 5
            targetCPUUtilizationPercentage: 90
            targetMemoryUtilizationPercentage: 175
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          pdb:
            enabled: true
            minAvailable: 1
            maxUnavailable: 0
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: monitoring

        configs:
          cm:
            create: true
            application.instanceLabelKey: argocd.argoproj.io/instance
            kustomize.buildOptions: --load-restrictor LoadRestrictionsNone
          rbac:
            create: true
            policy.csv: |
              g, argocd-admins, role:admin
              g, argocd-readers, role:readonly
            scopes: "[groups]"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m