---
- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: "0700"

- name: Generate ed25519 SSH keypair for user if absent
  community.crypto.openssh_keypair:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ ansible_user }}@{{ inventory_hostname }}"
    state: present

- name: Ensure private key permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
    state: file
    mode: "0600"

- name: Ensure public key permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
    state: file
    mode: "0644"