apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-tempo-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.logging.svc.cluster.local:3200
        editable: false
        jsonData:
          httpMethod: GET
          tracesToLogsV2:
            datasourceUid: P8E80F9AEF21F6940
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
            tags:
              - key: k8s.namespace.name
                value: namespace
              - key: k8s.pod.name
                value: pod
            filterByTraceID: true
            filterBySpanID: false
          nodeGraph:
            enabled: true
