---
- name: Check if node is already joined as worker
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Join worker node to cluster
  ansible.builtin.command:
    cmd: "kubeadm join --config {{ join_config_dir }}/join_kubeadm_wk.yaml"
  register: join_wk
  changed_when: join_wk.rc == 0
  when: not kubelet_conf.stat.exists