- name: Check if node is already joined as worker
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Copy join configuration file
  become: yes
  ansible.builtin.copy:
    src: /root/join_kubeadm_wk.yaml
    dest: /root/join_kubeadm_wk.yaml
    remote_src: yes
  when: not kubelet_conf.stat.exists

- name: Execute kubeadm join command for worker
  become: yes
  shell: "kubeadm join --config /root/join_kubeadm_wk.yaml"
  when: not kubelet_conf.stat.exists