---
- name: Join worker node to cluster
  ansible.builtin.command:
    cmd: "kubeadm join --config {{ join_config_dir }}/join_kubeadm_wk.yaml"
    chdir: "{{ join_config_dir }}"
  become: true
  args:
    creates: /etc/kubernetes/kubelet.conf