apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portal

resources:
  - namespace.yaml
  - workload.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - pbs-exporter

configMapGenerator:
  - name: homepage-config
    files:
      - settings.yaml
      - services.yaml
      - widgets.yaml
      - bookmarks.yaml
      - kubernetes.yaml
      - docker.yaml
      - proxmox.yaml
      - custom.css
      - custom.js
  - name: homepage-pve-ca
    files:
      - pve-root-ca.pem
  - name: homepage-assets
    files:
      - assets/portal-background.jpg

generatorOptions:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: homelab-portal
