---
- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Install required packages
  ansible.builtin.package:
    name:
      - curl
      - ca-certificates
      - apt-transport-https
      - gnupg
      - lsb-release
      - software-properties-common
      - jq
      - unzip
    state: present

- name: Install Docker
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: present

- name: Configure containerd
  ansible.builtin.shell: |
    mkdir -p /etc/containerd
    containerd config default | tee /etc/containerd/config.toml
    sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  notify: restart containerd

- name: Add Kubernetes apt key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /"
    state: present
  when: ansible_os_family == "Debian"

- name: Install Kubernetes packages
  ansible.builtin.package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_os_family == "Debian"

- name: Enable and start kubelet
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started

- name: Install Helm
  ansible.builtin.shell: |
    curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
    apt-get update
    apt-get install helm -y
  args:
    creates: /usr/local/bin/helm
  when: ansible_os_family == "Debian"

- name: Install Velero CLI
  ansible.builtin.unarchive:
    src: "https://github.com/vmware-tanzu/velero/releases/download/v1.14.1/velero-v1.14.1-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    creates: /tmp/velero-v1.14.1-linux-amd64/velero

- name: Copy Velero binary
  ansible.builtin.copy:
    src: /tmp/velero-v1.14.1-linux-amd64/velero
    dest: /usr/local/bin/velero
    mode: '0755'
    remote_src: true