---
- name: Join control plane to cluster
  ansible.builtin.command:
    cmd: "kubeadm join --config {{ join_config_dir }}/join_kubeadm_cp.yaml"
  register: join_cp
  changed_when: join_cp.rc == 0
  failed_when: false
  when: not ansible_facts['files'].get('/etc/kubernetes/manifests/kube-apiserver.yaml', False)
    chdir: "{{ ansible_env.HOME }}"
  become: true
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml