# このファイルは scripts/sync-cloudflare-secrets.sh によって生成されました。
# 編集する場合は 'sops kubernetes/infra/cloudflared/credentials.sops.yaml' を使ってください。
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:PN1ruAZooZLj12AtCHB0BR5whLXl9YhrMHVXvOcoJ1so9EMaExx08qv0s4yNVmPm2FWw37SCp7F/0zZf5KtcezEl5QfMuUzCcK9R63mnYPLIr/sjFJ+O9boDTXgPSQzuE6TZPwGBsUuHVhoQ671npIWY+768p6ewnflMY/ybudB9Xa/btNkJa7Y8WS2fF2rYzga1pzEYckYeazuYuASyHfmx82j7fFzoELQcqOLeht5zbG8uPTRbTVAlnA==,iv:R5CFJmjMlExaL/bENfE9lkfKLS9jieT/+CQYc+rFZ3s=,tag:IZSRT7N7Ao7tAsjG8C/QbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1R2RCYkRQT2lEaFRaNHQz
            aXhOeHFiQjNzWG5HRWgxdjk4aW51N0gya1dJCkZWYVFNUDZxb3BoRW1wOVZRdjFE
            WGZlZXJENkNVRVduRnhiMlg4TTdSZVkKLS0tIFVPRlh2dm1PSXJ3Q2FsWlljNmZx
            ZTFRaWY0M1RNZlUxQW43WFlPM0Vvc0UKeDkM51QQSfHb7Yexx+ie1DQwYOpSOn6a
            6H+PLKH4TaHHWMUmlCLaNKMClT8waQX8I6IIaMrJp0mFU3MRk4ATzQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mzq6plpzuyrzsp3l2gl6fnjxqztgmrk26ex923uxkj4khkzfdcuqjqjhcg
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T01:29:00Z"
    mac: ENC[AES256_GCM,data:XfWdYeHc0ptwHBF74PQruWQB2bE08jS3GUHUkriLolQwbn7szj3dfBE6svooxA/TDtgSBwC/GiwLhBGPvXzCGjq4VEgji+sxRYpse6WoCrgXiYRYNtUFK4iNl3LySKMA4mztXdQtTs/kTznmA0N2KHoAFj11W7fDdjp+0xigSXc=,iv:1z6ct0M4gOKZfBCs32iXx31Koxu3mbf8RjtquE5Ucwk=,tag:25cIevCDjcfTO+wgYkjOGA==,type:str]
    version: 3.13.3
