# このファイルは scripts/sync-cloudflare-secrets.sh によって生成されました。
# 編集する場合は 'sops kubernetes/infra/cloudflared/credentials.sops.yaml' を使ってください。
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: cloudflared
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:PN1ruAZooZLj12AtCHB0BR5whLXl9YhrMHVXvOcoJ1so9EMaExx08qv0s4yNVmPm2FWw37SCp7F/0zZf5KtcezEl5QfMuUzCcK9R63mnYPLIr/sjFJ+O9boDTXgPSQzuE6TZPwGBsUuHVhoQ671npIWY+768p6ewnflMY/ybudB9Xa/btNkJa7Y8WS2fF2rYzga1pzEYckYeazuYuASyHfmx82j7fFzoELQcqOLeht5zbG8uPTRbTVAlnA==,iv:R5CFJmjMlExaL/bENfE9lkfKLS9jieT/+CQYc+rFZ3s=,tag:IZSRT7N7Ao7tAsjG8C/QbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIaytseER4eFF4VUdabS8y
            enltUWIxSWdRNFV2NWdnUjc0TkhVc3pYVGlBCmRZZHBveXBxODEzVlVjRXR3Z0ZX
            ODMra2VhVENiZXBaWVpoeDJBNytFbHcKLS0tIEE5TmFkZFdYeC9WZUszeTZBRDM5
            ZjJVT21YcHhLR1k2dENvUlBpdTFhKzAKSa7TuG1bsESQvuiWzUOkl7RyoEtFxHtb
            w/8VwV8M6Rw083UGbSwcMu+PJEF700obdEmd6tJBD4ft/yGWyGMMSw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1r8scs39scqjnarmusdjk07jhew7uskwr3auz9ne9q3ljurvwv9uqsl0fjz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T01:29:00Z"
    mac: ENC[AES256_GCM,data:XfWdYeHc0ptwHBF74PQruWQB2bE08jS3GUHUkriLolQwbn7szj3dfBE6svooxA/TDtgSBwC/GiwLhBGPvXzCGjq4VEgji+sxRYpse6WoCrgXiYRYNtUFK4iNl3LySKMA4mztXdQtTs/kTznmA0N2KHoAFj11W7fDdjp+0xigSXc=,iv:1z6ct0M4gOKZfBCs32iXx31Koxu3mbf8RjtquE5Ucwk=,tag:25cIevCDjcfTO+wgYkjOGA==,type:str]
    version: 3.13.3
