apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: tempo
      targetRevision: 3.0.0
      helm:
        releaseName: tempo
        valueFiles:
          - $values/kubernetes/infra/tracing/tempo-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.12.1
      helm:
        releaseName: alloy-otel
        valueFiles:
          - $values/kubernetes/infra/tracing/alloy-otel-values.yaml
    - repoURL: https://github.com/craftzdev/homelab.git
      targetRevision: main
      path: kubernetes/infra/tracing/stack
    - repoURL: https://github.com/craftzdev/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: tempo
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.status
        - .spec.volumeClaimTemplates[]?.spec.volumeMode
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
