---
- name: Ensure sshd_config hardened settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^{{ item.key }}'
    line: '{{ item.key }} {{ item.value }}'
    insertafter: EOF
    backup: yes
  loop:
    - { key: 'PubkeyAuthentication', value: 'yes' }
    - { key: 'PasswordAuthentication', value: 'no' }
    - { key: 'PermitRootLogin', value: 'no' }
    - { key: 'ChallengeResponseAuthentication', value: 'no' }
  notify: Restart SSH

- name: Ensure AuthorizedKeysFile setting exists
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AuthorizedKeysFile'
    line: 'AuthorizedKeysFile .ssh/authorized_keys'
    insertafter: EOF
    backup: yes
  notify: Restart SSH